sudo: required
dist: trusty
language: scala

scala:
- 2.11.8
- 2.12.0-M4

env:
- JDK=oraclejdk8
- JDK=openjdk8

before_install:
  - sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y mosquitto

before_script:
  - jdk_switcher use $JDK

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
